name: Bundle

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  validate:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]

    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.ref }}

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"
      - name: Install requirements
        run: |
          python -m pip install --upgrade pip
          pip install -r dev_requirements.txt
      - name: Bundle
        run: |
          python -m nuitka \
            --standalone \
            --include-data-dir=source=source \
            --noinclude-data-files='*.json' \
            --remove-output
            --macos-create-app-bundle \
            --macos-app-icon=source/resources/icon.png \
            microcosm.py
        if: matrix.os == 'macos-latest'
