name: CI

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  validate:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest]

    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.ref }}

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"
      - name: Install system packages (Ubuntu)
        run: |
          sudo apt-get update -y
          sudo apt-get install -y libsdl2-2.0-0
        if: matrix.os == 'ubuntu-latest'
      - name: Install system packages (MacOS)
        run: |
          brew update
          brew install --cask vlc
        if: matrix.os == 'macos-latest'
      - name: Install requirements
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Lint
        run: pylint $(git ls-files '*.py')
      - name: Test
        run: python -m unittest discover -t source/tests/ -s source/tests/
